Add DataContextService - Database integration
harvestcore/matroos pull request #34
Opened 2022-04-19 14:45 UTC by harvestcore

2022-04-20 11:12 UTC, JJ commented
Every PR needs to have a description. At least the issues it addresses, and the technical decisions that have been taken. That said, it's probably too early for database integration.

2022-04-20 11:34 UTC, JJ requested changes
I have checked a file, and it consists of a few commits, none of which reference any issue, and thus any user story. *All* changes to the code need to be made guided by them; it's the only way to guarantee they add value to the client.
Biggest problem, however, is that I think adding data services is very premature. This PR should be done towards the end of the development. All business logic needs to be tested first.

2022-04-20 11:34 UTC, JJ commented on .github/workflows/test-dotnet.yml
> +      - name: Start MongoDB
This is *really* premature. You need to document all technical decisions you're taking. If you've chosen MongoDB, you need to say why and what is the state of the art in this area. But, as I say in #35, you need to organize development in progressively complex products; you can't even think about storage until you've designed and tested all relevant business logic.
Also, anything related to data storage needs to be mocked for testing. No need to start a real database for unit tests.

2022-04-20 11:34 UTC, JJ commented on backend/Matroos.Backend.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Matroos.Backend.Core", "src\Matroos.Backend.Core\Matroos.Backend.Core.csproj", "{4B396C9B-A5D0-4BA5-9307-84DD207F4C46}"
This file needs to be in the repo?

2022-04-20 11:34 UTC, JJ commented on backend/src/Matroos.Backend.Core/Classes/QueryFilter.cs
> +    public int Skip { get; set; } = 0;
You *never, ever* use getters and setters of everything unless a user story requires you to do so. Will this change after construction? Is this an object value or an entity? How has this been designed according to domain driven design (or other methodology)?

2022-04-20 11:34 UTC, JJ commented on backend/src/Matroos.Backend.Core/Services/DataContextService.cs
> +public class DataContextService : IDataContextService
I guess you have this for possible injection, nice.

2022-05-17 17:42 UTC, JJ commented
Is this left for later?

2022-05-17 17:54 UTC, harvestcore commented
> Is this left for later?

@JJ, yes. I've changed the PR to draft.

2022-06-29 18:28 UTC, harvestcore commented
Outdated, #31 is resolved in #89

2022-06-29 18:28 UTC, closed without merging