DOC-36 Problem to be solved.
harvestcore/matroos pull request #44
Opened 2022-05-11 18:26 UTC by harvestcore

This PR closes #36.

Includes documentation on the problem to be solved by the project. The documentation has been included in Markdown and in the final format, Latex. This has been included in the "Introduction" section.

2022-05-12 15:41 UTC, JJ requested changes
Si ya lo vas a incorporar, es conveniente que pongas ya el texto más o menos final, empezando por lo más importante, que es la motivación. ¿Qué hizo que quisieras hacer esta aplicación?
Por otro lado, igual el markdown bórralo ya, si repite el resto.

2022-05-12 15:41 UTC, JJ commented on doc/md/introduccion/introduccion.md
> +[Discord]([https://discord.com) es una aplicación de mensajería de uso tanto personal como en empresas. Es semejante a otras herramientas que se usan en ámbitos similares, como [Slack](https://slack.
Es mejor que empieces con el planteamiento del problema y la motivación al mismo.

2022-05-12 15:41 UTC, JJ commented on doc/md/introduccion/introduccion.md
> +Usuarios más avanzados (como por ejemplo, un administrador de sistemas, o alguien que controla distintos equipos) que quieren hacer uso de este software y de su sistema de bots se ven obligados a cre
Administrador ¿de qué sistemas?

2022-05-12 15:41 UTC, JJ commented on doc/md/introduccion/introduccion.md
> +Por tanto, se pretende desarrollar un framework para crear bots de Discord configurables que sean capaces de conectar con diferentes sistemas. La principal motivación a la hora de desarrollar este si
¿Qué problema soluciona esto y para quién?

2022-05-13 10:04 UTC, harvestcore commented
@JJ He aclarado los conceptos teniendo en cuenta tus comentarios, ahora debería estar mejor.

2022-05-14 17:18 UTC, JJ requested changes
Todavía tienes que intentar caracterizar el problema de forma un poco más clara. Esto se acerca más, porque aportas la información, sólo que está estructurada de una forma un poco compleja.

2022-05-14 17:18 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +En concreto, este proyecto se centra en los bots, que podrían definirse en este ámbito como herramientas que, haciendo uso de diferentes permisos, ayudan a automatizar tareas dentro de un servidor de
Deberías intentar introducir el proyecto lo más pronto posible.
- Primer párrafo: Existe el problema x 
- Segundo párrafo, "En concreto, en la plataforma Discord, que se ha hecho popular por..."
- Tercer párrafo "Resolver este problema puede ayudar a Y"

Fijarte desde el principio en la plataforma Discord hace que no abstraigas bien el problema, y por tanto el diseño de la aplicación sufra de acoplamiento alto y mala generalización. No creo que la plataforma Discord sea diferente de Telegram o Matrix esencialmente. De hecho, ahí tienes Matrix que sirve para conectar todas con todas. Cuanto más aclares desde el principio *el* problema que quieres solucionar más fácil será avanzar en el mismo.

2022-05-14 17:18 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +La principal motivación para realizar este proyecto es que crear bots para Discord con funcionalidades complejas con las herramientas actuales es prácticamente imposible. Si bien existen librerías pa
Arriba, primer párrafo: "Los bots permiten automatizar tareas en sistemas conversacionales. Sin embargo, su creación es muchas veces complicada"

En el tercer párrafo aclara si se trata de un problema específico de Discord, o simplemente es un problema general. El acoplamiento del problema a la plataforma debe hacerse lo más tarde posible en la fase de diseño. En general, la creación de bots es complicada en cualquier plataforma.

También deberías aclarar qué quieres decir con "funcionalidades complejas". ¿Quieres decir que guarden estado de una respuesta a otra? Tienes que caracterizar *el* problema desde el primer párrafo.

2022-05-14 17:18 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +No existen frameworks o sistemas que permitan crear fácilmente cualquier comando que uno quiera, y menos que sea reproducible o configurable con distintos parámetros. Un ejemplo de esto podría ser ha
¿Qué significa "que uno quiera"? ¿De qué casos de uso estás hablando en realidad? ¿Qué es lo que uno *quiere*? Una vez más, todo eso debería ir al primer párrafo de la intro.

2022-05-15 20:03 UTC, harvestcore commented
@JJ Debería estar mejor ahora.

2022-05-16 17:48 UTC, JJ requested changes
Ya voy entendiendo un poco más lo que quieres hacer, pero todavía me falta la motivación y aclarar el contexto en el que nos encontramos. También, tratándose de un trabajo de fin de máster, tendrías que intentar diferenciar claramente en lo específico de Discord y en lo que podría ser general para cualquier bot. Por ejemplo, ¿una biblioteca que haga parsing de mensajes para extraer comandos podría ser general?

2022-05-16 17:48 UTC, JJ commented on doc/tex/biblio.bib
> +@misc{discord,
No merece la pena que referencies esto como una entrada en la biblio a menos que haya algún texto específico. Pueden ser simplemente notas a pie de página

2022-05-16 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Los bots permiten automatizar tareas en sistemas conversacionales. Sin embargo, su creación en muchas ocasiones es compleja y no está al alcance de todos los usuarios. Existen tareas que son sencilla
Una vez más, me falta en el primer párrafo el "user journey", que proporcionaría contexto y motivación.
Adicionalmente, esto no está claro si es una definición o una afirmación. No tienes que suponer que el tribunal sabe lo que es. En la tercera frase te acabas perdiendo. ¿Dónde hay un gran volumen de datos? ¿En el sistema conversacional? ¿Qué quieres decir con automatizar? ¿Reaccionar? ¿Recopliar datos? ¿Repetir cada cierto tiempo?
Como te digo, un "user journey" ayudaría y permitiría entender la motivación.

2022-05-16 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +En concreto, en la plataforma \textit{Discord}\cite{discord}, que se ha hecho popular recientemente, este problema no es una excepción. En \textit{Discord} existen comunidades construidas en torno a
Insisto, no te "acoples" a Discord hasta que no sea estrictamente necesario. En general, los problemas que mencionas aparecen en cualquier plataforma conversacional, desde Telegram hasta, no sé, Mattermost.

2022-05-16 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Resolver este problema puede ayudar a todos aquellos usuarios y comunidades que buscan automatizar tareas específicas de manera individual sin tener que recurrir a terceros con los conocimientos espe
Aquí sí podrías mencionar específicamente Discord, o incluso en la motivación, pero insisto, todavía no se entiende lo que quieres hacer. ¿Una plataforma *no code* o *low code* para creación de bots? ¿Automatizar el despliegue de bots desde un UI específico, con la programación en otro lado? ¿Un IDE que ayude a programar bots?

2022-05-16 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +La principal motivación para realizar este proyecto es que crear bots para \textit{Discord} con funcionalidades muy concretas con las herramientas actuales es una tarea compleja. Si bien existen libr
¿Sólo para Discord? ¿Otras plataformas son más simples?

2022-05-16 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +No existen \textit{frameworks} o sistemas que permitan crear fácilmente comandos que se ajusten a necesidades específicas, y menos que sean reproducibles o configurables de alguna manera con distinto
No has introducido el concepto de "comando", así que es difícil que esto se entienda. También entiendo que los comandos se usan en cualquier plataforma de bots.

2022-05-16 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Como se indicaba en la sección anterior, usuarios con necesidades específicas (como por ejemplo podría ser un administrador de sistemas de una pequeña empresa, o incluso un usuario entusiasta al que
Entonces, ¿es una biblioteca para programación de bots en un lenguaje determinado? Si es así, ¿no deberías elegir un lenguaje más popular que C#? En función de los casos de uso y qué quieras hacer, habrá una serie de decisiones que vendrán determinadas por el mismo.

2022-05-16 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item \textbf{Usar bots ya existentes}. El bot ya se encuentra creado, configurado y desplegado, y solo es necesario agregarlo al servidor para poder disfrutar de sus funcionalidades.
Todo esto son diferentes casos de uso. Y no estás aclarando si lo que quieres hacer es las tres cosas, o bien sólo el segundo o el tercero.

2022-05-16 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Por tanto, se pretende desarrollar un \textit{framework} para crear bots de \textit{Discord} completamente configurables, y que además permita la creación sencilla de comandos. También, se busca tamb
¿Para hacer _qué aspecto_ de la creación de bots? ¿Una biblioteca para programar bots? ¿Un UI para desplegarlos? ¿Qué parte de la creación de bots se va a hacer y con qué lenguage? ¿Siempre con C#?

2022-05-16 23:27 UTC, harvestcore commented on doc/tex/secciones/01_introduccion.tex
> +Por tanto, se pretende desarrollar un \textit{framework} para crear bots de \textit{Discord} completamente configurables, y que además permita la creación sencilla de comandos. También, se busca tamb
He aclarado esto, debería estar mejor ahora.

> ¿Qué parte de la creación de bots se va a hacer...
- Crear el bot en sí, todo el código para que pueda ejecutarse y empezar a funcionar.
- Los comandos que se asignan a ese bot.

>  y con qué lenguaje? ¿Siempre con C#?
C#, y sí, siempre C#.

2022-05-16 23:35 UTC, harvestcore commented on doc/tex/secciones/01_introduccion.tex
> +Como se indicaba en la sección anterior, usuarios con necesidades específicas (como por ejemplo podría ser un administrador de sistemas de una pequeña empresa, o incluso un usuario entusiasta al que
Para lo que quiero hacer C# es el lenguaje que mejor se adapta. Quiero poder ejecutar tantos bots como quiera en segundo plano, y C# junto con .NET tienen un soporte para procesamiento en segundo plano muy bueno. Además, tratándose de bots los cuales seguramente tengan que responder a un número considerable de peticiones, el lenguaje y el framework tienen que poder responder a esto. JS es un lenguaje popular para crear bots de Discord, pero para estas tareas ofrece pocas herramientas y poco rendimiento. He trabajado con procesos en segundo plano con Python y no me ha gustado nada. Java es feo de por sí, y los demás... o bien tienen pocas librerías o tienen taras que no me convencen.

Por otro lado C# tiene librerías actualizadas regularmente para trabajar con Discord, y es un lenguaje que llevo utilizando un tiempo y con el que me siento cómodo.

2022-05-16 23:39 UTC, harvestcore commented on doc/tex/secciones/01_introduccion.tex
> +En concreto, en la plataforma \textit{Discord}\cite{discord}, que se ha hecho popular recientemente, este problema no es una excepción. En \textit{Discord} existen comunidades construidas en torno a
Entiendo, he mejorado ese aspecto. He intentado dejar Discord sin mencionar hasta justo el final. Debería estar mejora hora. Quizá me apoyé demasiado en [este comentario](https://github.com/harvestcore/matroos/pull/44#discussion_r873053785).

2022-05-16 23:40 UTC, harvestcore commented
@JJ :eyes:, please.

2022-05-17 15:36 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Como se indicaba en la sección anterior, usuarios con necesidades específicas (como por ejemplo podría ser un administrador de sistemas de una pequeña empresa, o incluso un usuario entusiasta al que
*Cualquier* lenguaje moderno puede con eso. JS no es multihebra, pero puedes hacerlo a nivel de sistema, simplemente trabajando con un sistema que cree rápidamente las hebras que sea. Si quieres hacer un framework monolítico donde se creen los blogs en una sola aplicación... Es una opción, pero no la mejor opción y desde luego no el único lenguaje (Elixir, Java, Go, por ejemplo... Y en este último tienes experiencia)

2022-05-17 15:44 UTC, JJ requested changes
Lo siento, pero es que tienes que entender esto como realmente es: el planteamiento del problema, no relleno para una memoria. Un proyecto siempre tiene que partir de un problema a resolver, no de una solución para un problema que no se sabe enunciar claramente, o que posiblemente no existe. No se pueden tomar de antemano una serie de elecciones (como el lenguaje) y buscar retro-justificación para las mismas. En un proyecto, y más en máster, tienen que justificarse absolutamente todas las decisiones técnicas de forma que maximicen el valor para el cliente.

2022-05-17 15:44 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Los bots permiten automatizar tareas en sistemas conversacionales. Sin embargo, su creación en muchas ocasiones es compleja y no está al alcance de todos los usuarios. Existen tareas que son sencilla
Sería conveniente que usaras un editor que te dividiera automáticamente la línea; es difícil comentar individualmente en un párrafo así.

Y perdona que insista, tienes que partir del problema. "Los bots permiten automatizar tareas" no es "el" problema. Ni siquiera sabes de qué tareas estás hablando, ni qué quieres automatizar. El user journey que te he comentado es una posibilidad, pero simplemente decir en qué momento pensaste "ojalá tuviera X para solucionar esto". 
Si lo que estás tratando es simplemente de poner relleno para hacer lo que querías hacer, una biblioteca de bots para Discord en C#, esto no va a servir ni funcionar. Si partes de lo que quieres hacer, nunca vas a llegar al problema que quieres solucionar, y por lo tanto va a ser imposible que soluciones ningún problema, sólo vas a hacer cosas que correspondan a la descripción general de lo querías hacer desde el principio.
En concreto, si para crear bots finalmente se tiene que usar una biblioteca en C#, la creación va a seguir siendo compleja y sin estar al alcance de todos los usuarios. Si lo que quieres hacer es otra cosa, por favor, acláralo.

2022-05-19 15:47 UTC, JJ approved these changes
Los cambios que quedan son de detalle, nada que bloquee.

2022-05-19 15:47 UTC, JJ commented on doc/tex/biblio.bib
> +@misc{enlyft,
Te digo lo mismo, no uses biblio para simples páginas web. Además, pueden cambiar.

2022-05-19 15:47 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +El uso bots se ha popularizado mucho recientemente, tanto es así que es raro no encontrarlos integrados en cualquier aplicación, ya sea de mensajería o de otros ámbitos. Éstos permiten automatizar cu
uso *de* bots.
También, "bots, *es decir*, ..." (puedes poner un ejemplo). Indica también el contexto en el que se ejecutan las órdenes, y dónde se ejecutan.

2022-05-19 15:47 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +En el caso de los sistemas conversacionales existen comunidades construidas en torno a multitud de ámbitos, como videojuegos, deportes, cine o incluso en el mundo profesional. Estas comunidades puede
... *por ejemplo*...

2022-05-19 15:47 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +De estos sistemas conversacionales destaca \textit{Discord}\cite{discord}, una aplicación de mensajería instantánea multiplataforma. Es semejante a otras herramientas que se usan en ámbitos similares
Si pones una cita, que sea un paper o artículo que hable de la popularidad de Discord.

2022-05-19 15:47 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item \textbf{Alto nivel}. Mediante el uso de herramientas \textit{no-code} que permite la creación sencilla de bots y comandos, obviando todos los detalles técnicos.
Aclara qué es un comando. Yo entiendo en Telegram por ejemplo que son tareas que se piden con comandos /, por ejemplo /loquesea x
Sin embargo, por lo que yo vi se trataba más bien de ciertas tareas fijas y establecidas que se combinaban. Por favor, aclara lo que quieres decir, si uno, otro, o los dos.

2022-05-19 20:40 UTC, merged