DOC-37 Add project objectives
harvestcore/matroos pull request #45
Opened 2022-05-11 18:31 UTC by harvestcore

This PR:
- Closes #37.
- Includes documentation about the project objectives (in both MD and Latex).

2022-05-17 17:48 UTC, JJ requested changes
Adolece de los mismos problemas que #44. Falta un problema concreto para un usuario concreto, y por tanto es muy complicado evaluarlo.

2022-05-17 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item  Diseñar y crear un \textit{framework} que permita crear, administrar y desplegar bots de \textit{Discord}.
Eso no es un objetivo, es una tarea. Por favor, mira el documento que os pasé sobre formulación de objetivos. Esencialmente, tiene que ser medible y tiene que estar siempre en el dominio del problema. Una vez más, por eso es esencial saber cuál es el problema y formularlo.

2022-05-17 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item  El \textit{framework} permitirá configurar comandos que permitan la administración de sistemas.
Una característica también y una tarea, no un objetivo.

2022-05-17 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item  El \textit{framework} se encontrará bajo licencia de software libre.
No es un objetivo tampoco, es simplemente un requisito. Un objetivo no puede cumplirse sólo diciendo "hala, aquí está la licencia".

2022-05-17 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item  El \textit{framework} creado permitirá la integración de distintas interfaces de usuario.
También es una característica. ¿Qué significa *integración*? ¿Para quién serán esas diferentes interfaces? Si no sabes qué problema resuelves ni para quién, es imposible formular los objetivos.

2022-05-17 17:48 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item  El tiempo de creación y despliegue de un bot de \textit{Discord} se reducirá al menos un 50%.
Esto sí tiene muy buena pinta. Pero no dices con respecto a qué. Ni cómo mides ese tiempo.

2022-05-20 15:38 UTC, JJ requested changes
Por favor, revisa bien el concepto de objetivo, que siempre está en el dominio del problema.

2022-05-20 15:38 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Finalmente, la elección de C\# no es arbitraria. Se fundamenta en el creciente número de bots que se están creando con este lenguaje y con las librerías existentes, además de la carencia de funcional
Si existen librerías, ¿qué aportas tú sobre ellas? ¿O vas a usarlas?
En todo caso, la justificación de las elecciones siempre es la misma.
* Tengo que elegir una herramienta que solucione el problema X
* Esa herramienta tiene estos requisitos
* Hay x herramientas que los cumplen.
* Elijo de todas ellas la herramienta Foo, que los cumple y además en grado x%.

Las elecciones siempre se justifican a priori, no a posteriori, y siempre basándose en las historias de usuario o casos de uso.

2022-05-20 15:38 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item  Diseñar y programar un sistema que sirva como capa de abstracción de la librería Discord.NET de C\# para crear bots y comandos de \textit{Discord}.
Esto es lo que vas a hacer, no un objetivo. ¿Qué problema y para quién quieres solucionar con esto? ¿En qué grado quieres solucionar el problema?

2022-05-20 15:38 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +	\item  El sistema permitirá desplegar los bots de manera sencilla y agnóstica a la infraestructura subyacente.
¿Qué problema quieres resolver?

2022-05-21 10:00 UTC, harvestcore commented on doc/tex/secciones/01_introduccion.tex
> +Finalmente, la elección de C\# no es arbitraria. Se fundamenta en el creciente número de bots que se están creando con este lenguaje y con las librerías existentes, además de la carencia de funcional
Ese párrafo es una introducción a lo que se va a usar. En el capítulo de herramientas es donde incidiré en todos los aspectos que comentas.

2022-05-21 11:14 UTC, harvestcore commented on doc/tex/secciones/01_introduccion.tex
> +	\item  El sistema permitirá desplegar los bots de manera sencilla y agnóstica a la infraestructura subyacente.
Aclarado este aspecto.

2022-05-21 11:14 UTC, harvestcore commented on doc/tex/secciones/01_introduccion.tex
> +	\item  Diseñar y programar un sistema que sirva como capa de abstracción de la librería Discord.NET de C\# para crear bots y comandos de \textit{Discord}.
Lo he aclarado algo más, debería estar mejor ahora.

2022-05-22 15:37 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Finalmente, la elección de C\# no es arbitraria. Se fundamenta en el creciente número de bots que se están creando con este lenguaje y con las librerías existentes, además de la carencia de funcional
En la introducción no se habla de lo que se va a usar, sino del problema que se quiere resolver.

2022-05-22 15:49 UTC, harvestcore commented on doc/tex/secciones/01_introduccion.tex
> +Finalmente, la elección de C\# no es arbitraria. Se fundamenta en el creciente número de bots que se están creando con este lenguaje y con las librerías existentes, además de la carencia de funcional
Mb, se me ha colado esto, lo quito.

2022-05-24 15:31 UTC, JJ reviewed
:+1: Pero tendrás que dejar muy claro *desde donde partes* en el estado del arte. Es decir, mostrar que hay aplicaciones actuales en las que es complicado drear bots, que se tarda mucho tiempo (y si dices que vas a reducir el 50%, tienes que *medir* ese tiempo) y así sucesivamente. Es decir, el estado del arte es fundamental, y en las conclusiones tendrás que referirte tanto a los objetivos como al estado del arte.

2022-05-24 15:33 UTC, JJ approved these changes
LGTM

2022-05-24 15:33 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +El desarrollo de este proyecto tiene los siguientes objetivos:
NO "El desarrollo", sino "este proyecto"

2022-05-24 18:29 UTC, merged