DOC-46 Add problem analysis documentation.
harvestcore/matroos pull request #47
Opened 2022-05-12 09:40 UTC by harvestcore

This PR closes #46, by:

- Adding the documentation related to the analysis of the problem.
  - Actors
  - Use cases
  - System requirements
  - Personas
  - User stories

To get the PDF: Go to the latest [action artifact](https://github.com/harvestcore/matroos/actions).

Ps: I'm aware that the spacing between tables and other elements may be a bit off in some cases. I'm not worried about this. The documentation will change a lot, and all the spacing issues will be fixed when the final document is ready to be shipped.

2022-05-17 17:59 UTC, JJ requested changes
Lo mismo, sigo un poco perdido, lo siento.

2022-05-17 17:59 UTC, JJ commented on doc/tex/biblio.bib
> +@misc{matroos,
Igual que en otros casos, una simple nota al pie es suficiente.

2022-05-17 17:59 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\begin{enumerate}
Un caso de uso está siempre en el dominio del problema, no enumera las diferentes opciones que va a haber. Eso tiene que resolverse en el programa.

2022-05-17 17:59 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item Crear bot.
De verdad que tienes que aclara un poco estas cosas. "Crear" puede ser desde programarlo desde cero hasta obtener un ID de bot hasta... no sé qué. "Crear" no es nada, ni has dicho qué problema quiere resolver el usuario, ni qué beneficio significaría crear el bot.
De hecho, ni siquiera has aclarado lo que es un bot. ¿Es simplemente reactivo? ¿Va a tener comandos? ¿Qué tipo de comandos? ¿Los comandos van a estar preprogramados?

2022-05-17 17:59 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item El \textit{backend} proveerá una \textit{API} capaz de funcionar sin la necesidad de una interfaz de usuario.
Esto es una descripción de una arquitectura, no un requisito funcional. Los requisitos funcionales vienen a decir dónde quieres ejecutar el framework, o cuanta gente va a haber, todo eso.

2022-05-17 17:59 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item La visualización de datos en la interfaz de usuario deberá ser en forma de listados.
Pero ¿dónde está como caso de uso la interfaz de usuario? ¿El usuario necesita una interfaz de usuario?

2022-05-17 17:59 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item El sistema funcionará para sistemas basados en \textit{GNU Linux}.
Igualmente, normalmente se trata de programar para que funcione en cualquier sistema.

2022-05-17 17:59 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item El sistema deberá ser escalable, esto incluye \textit{backend}, \textit{workers} e interfaz de usuario.
Escalable ¿de qué a qué?

2022-05-17 17:59 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Intereses & \textit{Discord}, ya que le parece una herramienta muy potente.\linebreak Videojuegos, le encantan los \textit{shooters}.\linebreak Automatización de tareas repetitivas, ya que od
¿Esto es relevante para la funcionalidad del problema? Usa también el entorno itemize

2022-05-21 17:23 UTC, harvestcore commented
@JJ He arreglado un montón de detalles. 👀 cuando puedas, gracias!

2022-05-21 18:40 UTC, JJ requested changes
En desarrollo ágil no existen los requisitos, existen las historias de usuario y los hitos. Ese es el principal error en esta revisión. El resto son temas de detalle...

2022-05-21 18:40 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +En el sistema hay dos actores, son los siguientes:
Quizás sería conveniente que dijeras qué beneficios obtienen cada uno del sistema. REcuerda también lo que he dicho en el grupo de Telegram sobre la (posible) monetización.

2022-05-21 18:40 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\begin{table}[H]
No tengo muy claro que este sea un cliente de ningún tipo, ni un "actor". Simplemente es una persona que va a interaccionar con el producto. Ten en cuenta que para cada actor va a haber una historia de usuario. Si tienes pensado incluir HUs para estos, OK.

2022-05-21 18:40 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\subsection{Administrador}
Insisto, actores son los que obtienen beneficios, no simplemente roles que pueda tener alguno de los clientes.

2022-05-21 18:40 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Propósito & Crear un bot para después configurarlos y desplegarlos. \\ \hline
En este caso, lo importante es dejar claro de qué forma va a funcionar esto. ¿Es un software como servicio multi-tenant que vaya a ser usado por diferentes usuarios? ¿O uno que alguien se instala y sólo va a ser usado por una persona?

2022-05-21 18:40 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item \textbf{R.F. 1} El sistema permitirá la administración de bots de \textit{Discord}. Esto incluye creación, modificación y eliminación de estos bots.
¿Por parte de un usuario? ¿De muchos usuarios? ¿Va a permitir "publicar" bots para que otros usuarios puedan "copiarlos" o "forkearlos"?

2022-05-21 18:40 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item \textbf{R.F. 2} El sistema permitirá la administración de comandos para bots de \textit{Discord}. Esto incluye creación, modificación y eliminación de estos comandos.
Tienes que escribir uno (o varios) *user journey*. ¿Qué significa "eliminar" comandos? ¿Que ya no se van a poder usar en ningún bot? ¿Cómo se escriben esos comandos? ¿Usando C#? ¿Un DSL?
Me da la impresión de que estás usando demasiadas especificaciones antes de plantearte una serie de PMVs como hablamos por video. Yo haría una serie de casos de uso minimalistas, y empezaría por ellos.

2022-05-21 18:40 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item \textbf{R.F. 3} Los comandos podrán reutilizarse con distintos parámetros, pudiendo ser asignados a distintos bots.
Si vas a usar desarrollo ágil, eso va en contra de tener tantos requisitos desde el principio. El desarrollo ágil no es ir sacando dos RFs por sprint, es ir elaborando estos requisitos basado en los resultados de los PMVs anteriores.

2022-05-22 11:54 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +\begin{table}[H]
Cierto, no tiene mucho sentido este actor, lo quito.

2022-05-24 21:10 UTC, harvestcore commented
@JJ He agregado los _user journeys_ y el modelo de negocio. Cuando puedas échale un ojo, ty!

2022-05-26 15:52 UTC, JJ requested changes
Seguimos con el problema de siempre: tú tienes muy claro qué quieres hacer desde el principio, y todo el contexto, pero para una persona que lo lea se pierde. También tienes claras las decisiones que has tomado, y estás tratando de justificarlas proyectándolas como "casos de uso". Tienes que aclarar dos cosas
1. *Siempre* se trata de problemas que resolver. Pon esos problemas, no pongas lo que tú crees que hay que hacer para resolverlos. Nunca hay una sola forma de resolverlos. Dependiendo del problema, un bot (sea lo que sea) se puede borrar por parte del usuario, se puede borrar automáticamente cuando suceda X, o se puede definir de forma que sólo funciona mientras suceda Y
2. Aclara qué quieres decir con cada cosa. Un bot puede ser: un programa ejecutándose, un programa almacenado, las dos cosas, ninguna de las cosas, un programa que se interpreta para genera un bot, un "hook" preescrito... Puede ser muchas cosas diferentes. Teniendo en cuenta el problema que quieres resolver, será una u otra cosa. Igual que "comandos" o "workers"

2022-05-26 15:52 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +En este capítulo se profundiza en el análisis del problema planteado en capítulos anteriores, describiendo los diferentes actores, casos de uso, historias de usuario y los \textit{user journeys} asoc
Por favor, no cambiéis el nombre con mv, sino con `git mv`. Así se ven más claramente los cambios, y no tengo que revisarlo todo desde cero.

2022-05-26 15:52 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Descripción & Crea los bots y los comandos. Tiene poder de configuración y de despliegue. Puede ser también usuario del bot haciendo uso de sus comandos. Agrega los bots a los servidores de \
No sé si has definido comandos ya, pero *tienes que hacerlo*. De veras que no entiendo bien todavía lo que quieres decir. Si son recetas pre-escritas que pueden combinarse de cualquier forma para montar un bot, dilo así (pero esto sería un lenguaje, no "comandos": comandos unos detrás de otros forman un lenguage)

2022-05-26 15:52 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Propósito & Crear un bot para después configurarlos y desplegarlos en distintos \textit{workers}. \\ \hline
Tampoco has definido worker. Y cuando lo hagas, tendrás que definir "desplegar"

2022-05-26 15:52 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        \textbf{Caso de uso} & \textbf{03 - Eliminar un bot} \\ \hline
Esto no son casos de uso, son simples tareas que quieren hacer. Los casos de uso son siempre problemas que el usuario quiere resolver. ¿Qué problema resuelve borrándolo? No pongas como casos de uso las tareas que tú crees que puede hacer el usuario, sino los problemas reales que quieres resolver (porque dependiendo del problema, se puede resolver de muchas formas diferentes)

2022-06-01 19:05 UTC, harvestcore commented
@JJ He actualizado el PR. Revísalo cuando puedas, gracias.

He simplificado las historias de usuario (y borrado algunas). Las que están creadas como issues en este repo las actualizo en cuanto este PR esté aprobado.

He actualizado también los user journeys, quitando palabras no definidas previamente.

2022-06-05 17:47 UTC, JJ requested changes
Por favor, revisa bien el concepto de historia de usuario, aparte de desambiguar conceptos.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +En este capítulo se profundiza en el análisis del problema planteado en capítulos anteriores, describiendo las diferentes personas, historias de usuario y los \textit{user journeys} asociados a estas
Si lo que has hecho es cambiarlo de nombre, por favor usa siempre git mv, aunque al final sea otra cosa diferente, así se ve claramente qué es lo que has cambiado.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Necesidades & Un software o sistema que le permita programar las tareas repetitivas de monitorización y automatización que tanto odia. Usa mucho \textit{Discord}, por lo que piensa que sería
No queda nada claro por qué tiene que hacer tareas repetitivas, ni en qué consisten las tareas repetitivas.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Frustraciones & No le gusta nada tener que indagar en detalles técnicos al jugar a videojuegos con sus amigos. Entiende que en ocasiones es necesaria alguna configuración para poder jugar (co
Detalles técnicos ¿de qué?

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Necesidades & Una herramienta que le permita acceder a esos detalles sin preocuparse de recordarlos o de consultarlos de manera extraña. \\ \hline
¿De qué detalles estamos hablando y cómo quiere acceder a esos detalles?

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Meta & Creación de bots para que más tarde puedan ser configurados con distintas funcionalidades. \\ \hline
¿Por qué *más tarde*? ¿Los bots no son inmutables? ¿Hay algún requerimiento que haga que se tengan que cambiar sobre la marcha?

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Beneficio & De este modo, cada bot puede tener una funcionalidad específica configurada, sin tener que compartir un bot con funcionalidades de distintos ámbitos. \\ \hline
El beneficio tiene que estar en el espacio del problema, no en el espacio de la solución. El único problema que hay formulado es la necesidad de "automatizar" (no está muy claro por qué, ni qué) y la necesidad de ¿ver detalles técnicos? Estás formulando soluciones al problema y las estás poniendo como el mismo problema, y no lo son.
Es decir, tienes que llegar a la solución de forma natural y como parte del proceso de empatizar con el usuario.
En los dos casos, tienes que expresar claramente el beneficio que proporciona automatizar "tareas", y hacerlo en Discord. ¿Se juega mejor? ¿Se ganan más partidas? ¿Hay, no sé, "consciencia situacional"?
Igual para el otro caso, "buscar".

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Escenario & · Dado: que quiero crear distintos bots de \textit{Discord} y configurar sus funcionalidades,\linebreak · Cuando: proveo al sistema de los datos necesarios,\linebreak · Entonces:
"crear bots" no está en el dominio del problema. "Ganar más partidas" "Perder menos tiempo haciendo no sé qué" está en el dominio del problema. Son cuantificables, y por tanto son objetivos medibles que tu software puede alcanzar, y se puede demostrar que se ha alcanzado.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Notas funcionales & · No se debe permitir colisiones entre parámetros identificadores de los bots. \\ \hline
Esto no tiene nada que ver con un perfil de usuario. Es un issue técnico que debe resolverse, pero no forma parte de historia de usuario. Los detalles de implementación deben ser totalmente transparentes al usuario.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario administrador quiero poder editar los detalles de un bot, para configurarle comandos nuevos, eliminar existentes o cambiar sus parámetros. \\ \hline
¿Qué problema resuelve esto? Insisto, si ponemos siempre lo que queremos hacer antes de lo que hay que resolver, acabamos con soluciones que pueden ser subóptimas, o que realmente no solucionan el problema. ¿Para qué hace falta editar un bot? ¿No será mejor que haya robots inmutables? Si editas los detalles de un bot, ¿lo redespliegas en producción? ¿Borras todas las instancias que estén funcionando?
Insisto, esto sigue sin ser una historia de usuario, que tiene que estar siempre en el espacio del problema, y siempre proporcionar un beneficio al usuario.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Beneficio & Ampliar, reducir o modificar las funcionalidades específicas de los bots. \\ \hline
No es un beneficio, es una tarea. Beneficio sería la razón por la que quieres hacer eso. E, insisto, piensa siempre *primero* en lo que quieres resolver, y luego en lo que quieres hacer para resolverlo.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Escenario & · Dado: que quiero modificar los datos de los bots,\linebreak · Cuando: proveo al sistema de los datos que se quiero modificar,\linebreak · Entonces: el sistema modifica esos dato
Estoy viendo que voy a poner lo mismo en cada lugar. ¿Por qué quieres modificar los datos de los bots? ¿Eso te va a ayudar a "automatizar tareas" o a "buscar"? ¿Qué problema específico resuelve?

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Criterio de aceptación & · El bot es modificado correctamente.\linebreak · El usuario es avisado en caso de error al modificar los datos del bot.\linebreak · Tests unitarios y integración son
Además de todos los problemas anteriores, no has definido "bot" correctamente. Un bot esencialmente es un programa. Y ese programa estará ejecutándose o no. Cuando hablas de "bot", no aclaras de si se trata del programa o de todas las instancias del programa que están desplegadas, y/o ejecutándose. Como no tienes ningún problema en mente, causas un problema adicional que es la ambigüedad bot/bot desplegado y qué es lo que se va a hacer cuando modifiques un bot con los bots desplegados.
El problema principal es que todo esto son esencialmente issues, y es un error ir poniendo estos issues antes de encontrarse con un producto mínimamente viable que lo necesite.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario administrador quiero disponer de un repertorio de comandos predefinidos ampliable para después crear comandos personalizados a partir de ellos. \\ \hline
Si lo que quieres es automatizar tareas, ¿para qué quieres comandos? ¿Qué significa "a partir de ellos"? ¿Sólo puedes cambiar alguno existente?
Una vez más, esto es más definición de un PMV que una historia de usuario. Y no un PMV de los primeros.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\subsection{HU-06 - Lanzar bots}
Esto es un issue también. O ni siquiera eso, porque si no lanzas un bot ni siquiera podría funcionar. Así que iría implícito con cualquier historia de usuario.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Meta & Desplegar bots para que puedan usarse desde los servidores de \textit{Discord}. \\ \hline
Desplegar, ¿dónde? Si no defines claramente la *persona* del administrador, esta tarea no tiene ningún sentido. Desplegar puede ser desde subir a Amazon, hasta simplemente ejecutarlo desde la línea de órdenes, pasando por Raspis, PaaS... La *persona* tiene que definir qué tipo de recursos tiene para que se haga algo razonable, y no simplemente lo que has decidido hacer desde el principio.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Beneficio & La ejecución de los bots permite que los comandos estén disponibles en los servidores de \textit{Discord} para los usuarios. \\ \hline
¿Servidores o canales?

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario administrador quiero que las configuraciones de bots y comandos sean persistentes, de modo que no pierda el trabajo realizado. \\ \hline
Esto es también obvio. Nadie quiere perder ningún trabajo realizado. También es un detalle de implementación.

2022-06-05 17:47 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\subsection{HU-08 - Interfaz de usuario}
Voy a dejarlo aquí. Creo que ya deberías tener claro qué es y qué no es una historia de usuario.

2022-06-06 20:57 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +En este capítulo se profundiza en el análisis del problema planteado en capítulos anteriores, describiendo las diferentes personas, historias de usuario y los \textit{user journeys} asociados a estas
El archivo anterior estaba vacío, o sea que el archivo este es revisable al completo.

2022-06-06 21:42 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Meta & Creación de bots para que más tarde puedan ser configurados con distintas funcionalidades. \\ \hline
No tiene sentido que un bot sea inmutable, porque se puede querer cambiar sus funcionalidades agregando/quitando comandos. Lo cambio aún así para aclararlo.

2022-06-06 22:08 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario administrador quiero poder editar los detalles de un bot, para configurarle comandos nuevos, eliminar existentes o cambiar sus parámetros. \\ \hline
Si quiero agregar un nuevo comando al bot, no tiene mucho sentido que el bot sea inmutable, por lo que se tendría que volver a desplegar ese bot.

2022-06-06 22:18 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Escenario & · Dado: que quiero modificar los datos de los bots,\linebreak · Cuando: proveo al sistema de los datos que se quiero modificar,\linebreak · Entonces: el sistema modifica esos dato
Quizá no te entiendo o no me estoy expresando como debería en lo escrito en la memoria. Veo el modificar los bots un problema bastante específico.

Digamos que tengo un bot con 3 comandos: !hola, !adios y !help, que devuelven tres mensajes por pantalla. Si quiero agregar un nuevo comando a este bot tendré que modificarlo, ¿no?. ¿Qué sentido tiene tener un bot inmutable que no cambia nunca? En caso de que fueran inmutables podría crear otros nuevos, pero entonces llegaría un punto donde tendría 50 bots distintos con X comandos en cada uno.

Entiendo que "modificar datos" no es lo más expresivo, cambio eso para que quede mas claro.

2022-06-06 22:28 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Criterio de aceptación & · El bot es modificado correctamente.\linebreak · El usuario es avisado en caso de error al modificar los datos del bot.\linebreak · Tests unitarios y integración son
El software no es un bot que ejecuta bots, no tendría sentido. La definición de bot se agrega en [este PR](https://github.com/harvestcore/matroos/pull/57).

En caso de modificar un bot ya desplegado, habría que volverlo a desplegar si se quiere disponer de las últimas modificaciones realizadas.

2022-06-06 22:34 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario administrador quiero disponer de un repertorio de comandos predefinidos ampliable para después crear comandos personalizados a partir de ellos. \\ \hline
No quiero automatizar tareas como si fueran procesos en segundo plano que están siempre ejecutándose. El problema es que crear bots con funcionalidades concretas es un coñazo, porque las herramientas actuales son demasiado básicas. 

Quiero disponer de un conjunto de comandos "plantilla" ampliable que me permita crear múltiples comandos personalizados _a partir de ellos_.

Por ej:
**Crear comandos personalizados:** Existe un comando predefinido para enviar mensajes. A partir de ese comando predefinido/plantilla puedo crear 190 comandos distintos que manden 190 mensajes distintos.

**Crear un comando predefinido/plantilla:** Aquí sí que necesito crear código, con C# y demás

2022-06-06 22:36 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Beneficio & La ejecución de los bots permite que los comandos estén disponibles en los servidores de \textit{Discord} para los usuarios. \\ \hline
Los bots se agregan a los servidores, dentro de estos hay canales de texto, voz, etc

2022-06-07 12:27 UTC, harvestcore commented
@JJ Revisa cuando puedas, please.

2022-06-07 15:46 UTC, JJ reviewed
Por favor, intenta responder a las preguntas que te hago para ver si avanzamos hacia los problemas que se quieren resolver. No sirve de nada proponer un montón de tareas si no tienes, de antemano, claro qué problema vas a resolver y si lo resuelves o no.

2022-06-07 15:46 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Escenario & · Dado: que he detectado tareas que se podrían simplificar haciendo uso de comandos de bots de \textit{Discord},\linebreak · Cuando: creo y configuro los bots,\linebreak · Entonce
Una vez más. Estás igualando "comandos" a "tareas", y estás básicamente diciendo que hay tareas que se pueden automatizar con un bot. Sigo sin tener muy claro qué tareas son, pero parece que son simplemente secuencias de mensajes, o quizá un solo mensaje. También tendrías que aclarar qué es "automatizar". Si es repetir con una frecuencia determinada, es simplemente repetir. Automatizar implicaría alguna forma de grabar las tareas.
En todo caso, el problema es el habitual: sigues diciendo qué quiere hacer, no por qué quiere hacerlo. O mejor dicho, qué quiéres tú que él te pida, y no qué problema quiere resolver. Si dejaras claro qué es lo que se automatiza y por qué se automatiza, quizás se entendería un poco mejor por qué quiere la gente automatizarlo. Para el caso, es que no entiendo muy bien qué relación tiene Discord con el juego en sí, ni si se hacen cosas para juegos específicos, o simplemente canales específicos...
Siempre en un proyecto tienes que empezar por aclarar qué problema quieres resolver, si no todo se disuelve en ambigüedades, y sobre todo la "solución" que proporcionas es imposible saber si *realmente* soluciona algo.

2022-06-07 15:46 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Criterio de aceptación & · Los bots y los comandos se pueden crear correctamente.\linebreak · El usuario es avisado en caso de error.\linebreak · Tests unitarios y integración son creados den
Es que aquí tienes el problema. Un criterio de aceptación no puede ser nunca aceptar cualquier cosa. Si no resuelve el problema, no lo puedes aceptar. 
Y una vez más, "crear bots" son tareas. Esto puede se rmuy bien un issue asociado a una historia de usuario, porque imagino que sea lo que sea un bot habrá que crearlo, pero los criterios de aceptación están siempre en el *espacio del problema*

2022-06-07 15:46 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\subsection{HU-02 - Editar bots y comandos}
Una vez más, es un issue. Pero un issue tiene que tener siempre una historia de usuario === un problema.

2022-06-07 15:46 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario administrador quiero poder cambiar la funcionalidad de los bots, ya que es posible que en ocasiones necesite ampliar o reducir sus comandos, o cambiar lo que estos coma
¿Qué problema resuelves con eso? Esto seguirá sin ser una historia de usuario, pero si tratas de entender *que tienes que resolver problemas* y que *esos problemas son los que se ponen en la historia de usuario* avanzaremos un poco hacia la aceptación de esta parte de la memoria.

2022-06-07 15:46 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario administrador quiero disponer de un repertorio de comandos predefinidos ampliable para después crear comandos personalizados a partir de ellos. \\ \hline
> No quiero automatizar tareas como si fueran procesos en segundo plano que están siempre ejecutándose. El problema es que crear bots con funcionalidades concretas es un coñazo, porque las herramientas actuales son demasiado básicas.
> 
> Quiero disponer de un conjunto de comandos "plantilla" ampliable que me permita crear múltiples comandos personalizados _a partir de ellos_.

* HU: Como *programador* quiero poder crear nuevos bots de forma fácil a partir de otros existentes. * Tu cliente es un programador, no un usuario.

> 
> Por ej: **Crear comandos personalizados:** Existe un comando predefinido para enviar mensajes. A partir de ese comando predefinido/plantilla puedo crear 190 comandos distintos que manden 190 mensajes distintos.
> 

Eso son detalles de implementación o posibles soluciones al problema, que corresponderán en un issue y un MVP posterior.

> **Crear un comando predefinido/plantilla:** Aquí sí que necesito crear código, con C# y demás

Por eso la *persona* tiene que ser un programador. Y para planificar el proyecto tendrás que organizar los diferentes MVPs para que se *pase* por este tarde o temprano.

2022-06-07 15:46 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\begin{enumerate}
Un user journey debe reflejar la frecuencia, el contexto y el modo de uso del sistema por parte de las diferentes personas. Son detalles relevantes a la hora de resolver el problema que tiene. Que reciba un token o no es irrelevante. Lo relevante es cuando se da cuenta que necesita un bot, cuantos bots nuevos va a hacer, si los bots nuevos los desarrolla a partir de los antiguos y cosas así. Están relacionados con las historias de usuario, no con las tareas que tú vayas a hacer y mucho menos describe una situación de uso posible de tu aplicación.

2022-06-07 15:46 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +Se puede modificar un bot de dos maneras:
Una vez más, no un user journey. Un user journey describiría en qué circunstancias uno necesitaría modificar un bot.

2022-06-07 21:36 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Escenario & · Dado: que he detectado tareas que se podrían simplificar haciendo uso de comandos de bots de \textit{Discord},\linebreak · Cuando: creo y configuro los bots,\linebreak · Entonce
> Una vez más. Estás igualando "comandos" a "tareas",

Los comandos ejecutan las tareas. No los estoy viendo como iguales.

> y estás básicamente diciendo que hay tareas que se pueden automatizar con un bot.

Sí. En lugar de tener que hacer yo esa tarea (enviar un mensaje o enviar un tweet o lo que sea) lo puede hacer el bot cuando ejecuto un comando.

> Sigo sin tener muy claro qué tareas son, pero parece que son simplemente secuencias de mensajes, o quizá un solo mensaje.

Puede ser cualquier cosa programable de alguna manera en un bot. Utilizo mucho el ejemplo del mensaje porque lo veo sencillo, pero podría ser cualquier cosa: mandar un tweet, consultar algo en alguna API, descargar cosas, ...

De ahí del problema, que las herramientas que existen actualmente no permiten automatizar en un comando cualquier tarea. Se centran en enviar mensajes y poco más, si un usuario quiere un bot que (por ejemplo) haga peticiones PING a un servidor en China y luego postee un tweet con esa información, pues tiene que buscarse la vida programándolo él, porque las herramientas que hay no se lo permiten.

> También tendrías que aclarar qué es "automatizar". Si es repetir con una frecuencia determinada, es simplemente repetir. Automatizar implicaría alguna forma de grabar las tareas.

Seguramente no lo esté expresando de la mejor manera, pero realmente automatizar es básicamente que el bot se encargue de ello. Si puedo crear y configurar un comando para que se haga cuando ejecuto !micomando en lugar de hacerlo yo a mano, ya estoy automatizando cosas.

> En todo caso, el problema es el habitual: sigues diciendo qué quiere hacer, no por qué quiere hacerlo. O mejor dicho, qué quiéres tú que él te pida, y no qué problema quiere resolver.

No lo veo de esa manera. Es cierto que el usuario no es el típico, ya que tiene conocimientos de programación y demás, y seguramente no lo esté expresando bien. El problema que quiere resolver es crear bots y comandos de manera sencilla, que le permitan hacer lo mencionado.

> Si dejaras claro qué es lo que se automatiza

Cualquier tarea, la que el usuario quiera (siempre que sea programable, obviamente).

> y por qué se automatiza, quizás se entendería un poco mejor por qué quiere la gente automatizarlo.

Para que el usuario no tenga que hacerlo a mano. Ejecutar un comando y que el bot se encargue de hacer cosas es mucho más cómodo que tener que hacer esas cosas yo.

> Para el caso, es que no entiendo muy bien qué relación tiene Discord con el juego en sí, ni si se hacen cosas para juegos específicos, o simplemente canales específicos...

No entiendo lo del "juego". Discord es una plataforma muy utilizada últimamente, con integración de bots muy buena que permite hacer un montón de cosas. Se podrían crear bots para otras plataformas/apps, pero entre usuarios "programadores", lo que más veo que se use es Discord. Aparte, que el resto de usuarios no "programadores" también lo usan. Hay grupos de gente que lo usan para juntarse a jugar a X videojuego e integran bots para escuchar música o para moderar.

> Siempre en un proyecto tienes que empezar por aclarar qué problema quieres resolver, si no todo se disuelve en ambigüedades, y sobre todo la "solución" que proporcionas es imposible saber si realmente soluciona algo.

[Aquí](https://github.com/harvestcore/matroos/pull/57) debería estar mejor definido el problema.

2022-06-07 21:55 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Criterio de aceptación & · Los bots y los comandos se pueden crear correctamente.\linebreak · El usuario es avisado en caso de error.\linebreak · Tests unitarios y integración son creados den
Cierto, lo cambio en todas las HU.

2022-06-07 22:00 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +\subsection{HU-02 - Editar bots y comandos}
Lo sigo viendo en parte como un problema. Es posible que se necesite ampliar o reducir la funcionalidad de los bots, o cambiar lo que hacen los comandos (por X o Y motivo).

Se podría sobreentender que eso se quiere hacer (como pasa al lanzar los bots, que no necesita HU), en ese caso lo quito como HU.

2022-06-07 22:02 UTC, harvestcore commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario administrador quiero poder cambiar la funcionalidad de los bots, ya que es posible que en ocasiones necesite ampliar o reducir sus comandos, o cambiar lo que estos coma
> ¿Qué problema resuelves con eso?

Que los bots/comandos no sean inmutables. Es parte del problema que las herramientas actuales se basan en la creación de bots/comandos que apenas se pueden modificar (o que directamente no se pueden tocar).

2022-06-08 16:39 UTC, JJ requested changes
Seguimos con una serie de problemas de base. A ver si centrándonos en identificar clientela/problema a resolver podemos seguir adelante.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item El programador, cuando se encuentra interactuando con otros usuarios en Discord, detecta una serie de funcionalidades (como enviar mensajes de alerta a todos los usuarios, o asignar un rol a c
¿Por qué necesita un bot para eso? ¿No se pueden hacer directamente desde el interfaz? También, ¿qué beneficio obtiene enviando mensajes de alerta o asignando roles? Recuerda que tienes que fijarte en *un* problema. También ayudaría si listaras las funcionalidades de Discord y cuales están o no están disponibles desde el cliente que se use.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item El programador comprueba cada semana las necesidades que tienen los usuarios de los servidores de Discord donde ha agregado bots previamente. Si estas funcionalidades están obsoletas, las actu
¿Por qué hace eso el administrador? ¿Cómo lo hace? ¿Cómo defines necesidades? ¿Las funcionalidades ocupan espacio? ¿Suponen un gasto?
Es que también me falta que expliques "serie de funcionalidades". Si no eres preciso, la audiencia no puede saber si esto lo estás haciendo y realmente estás añadiendo algún valor a un cliente de discord o qué es lo que estás haciendo.
En otro orden de cosas, lo que dices aquí no tiene mucho sentido, que sólo se mantengan las "funcionalidades" (sea como sea la definición de eso) que se han usado la última semana. Si sigues así te quedas sin funcionalidades.
Y también es un ejemplo de lo que se está haciendo desde el principio: tienes claro que quieres hacer, y tratas de ajustar las HUs, hitos, user journeys y demás de forma que lo que querías hacer desde el principio tenga sentido. No ha funcionado hasta ahora, y no va a funcionar.
Mira [este tutorial, por ejemplo, sobre todo los pasos 2 y 3](https://uxplanet.org/a-beginners-guide-to-user-journey-mapping-bd914f4c517c)
Recuerda que siempre un producto tiene que crear valor para el cliente o clientes, ofrecerle cierto beneficio. Si un user journey no muestra claramente cuál es el problema y ofrece contexto, no es útil y puedes simplemente suprimirlo.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item Cuando el programador detecta una funcionalidad que no puede configurar con el sistema en un bot, implementa esa funcionalidad para poder usarla en el sistema. Sabiendo que la interacción que
Sigues usando "funcionalidad" como si de repente el Discord echara dientes o hablara en euskara o algo; sigues escribiendo el user journey para ti mismo, y no para personas, como yo o el tribunal, que no han usado Discord nunca.
Sin embargo, este sí ofrece una experiencia de usuario que puede ser útil, y plantea un problema: el cliente tiene que reaccionar a las nuevas "funcionalidades" (sea lo que sean).
Pero la cuestión es que, con tu proyecto, tienes que resolver *ese* problema. Es decir, tienes que crear un MVP que sea capaz de "detectar" nuevas funcionalidades y ofrecerle al cliente una forma fácil de ofrecer soluciones basadas en las mismas. Estás hablando de [observabilidad](https://empresas.blogthinkbig.com/observability-que-es-que-ofrece/) y por tanto tienes que crear, para empezar, una herramienta de observabilidad. Ese sería el MVP, y de este user journey podría salir una historia de usuario.
Que eso no es lo que querías hacer, no me vale. Tienes que *querer hacer* algo que resuelva algún problema, no ofrecer soluciones fijas a problemas mal definidos, porque por definición esas soluciones no van a resolver ningún problema real.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +	\item \textbf{Actualizar cuando las issues estén creadas en GitHub.}
Pon esto como un comentario.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario programador, cuando detecto alguna tarea que se puede simplificar en un bot, quiero poder crear distintos bots de \textit{Discord} para poder configurar comandos en ell
Esto está relacionado con el user journey que he comentado antes. Una vez más, la palabra clave y el problema es "detectar". Pero como siempre, tienes que definir "tarea", "simplificar"
El problema es que, desde cero, en la introducción no has explicado claramente qué es el contexto, qué "tareas" son tan específicas de Discord y de los juegos, y en qué contexto estamos manejándonos. Porque puede ser tan general que sea irresoluble, o tan específico que se pueda resolver de una forma muy simple, creando un par de bots y no todo un framework para crear y desplegar bots. Pero para ello hay que tener bien claro cuál es el problema y su alcance.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Escenario & · Dado: que he detectado tareas que se podrían simplificar haciendo uso de comandos de bots de \textit{Discord},\linebreak · Cuando: creo y configuro los bots,\linebreak · Entonce
> > Una vez más. Estás igualando "comandos" a "tareas",
> 
> Los comandos ejecutan las tareas. No los estoy viendo como iguales.

Hablas de "comandos", "tareas", "funcionalidades", sin claramente definir cada uno de los términos, lo que puede dar lugar a confusión (y de hecho, no lo entiendo yo)
> 
> > y estás básicamente diciendo que hay tareas que se pueden automatizar con un bot.
> 
> Sí. En lugar de tener que hacer yo esa tarea (enviar un mensaje o enviar un tweet o lo que sea) lo puede hacer el bot cuando ejecuto un comando.

¿Y qué ganas ejecutando un comando en vez de escribiendo el mensaje? ¿Repites un mensaje tantas veces que teclear /msg 3 en vez de "Vienen los malos" representa alguna ventaja?

De verdad que tienes que hacer un esfuerzo por explicar bien el contexto, porque hay algo que se me pierde. Entiendo que en un entorno donde te están pegando tiros todo el rato, ahorrar 3 segundos de tecleo puede ser una ventaja competitiva. Pero *tienes que explicar claramente ese mensaje*. Al final, es que tienes que explicar claramente *cuál es el problema que quieres resolver*. Si es "ahorrar segundos para poder ser más competitivo en el juego", lo tienes que explicar de forma clara y precisa.
> 
> > Sigo sin tener muy claro qué tareas son, pero parece que son simplemente secuencias de mensajes, o quizá un solo mensaje.
> 
> Puede ser cualquier cosa programable de alguna manera en un bot. Utilizo mucho el ejemplo del mensaje porque lo veo sencillo, pero podría ser cualquier cosa: mandar un tweet, consultar algo en alguna API, descargar cosas, ...

Ese *no* es el problema que tratas de resolver. Si no defines claramente el problema, no puedes proporcionar valor al cliente a través de una solución. Dicho de otro modo, decir que *puede ser cualquier cosa* indica que *no sabes qué problema estás resolviendo* y por tanto es imposible que lo resuelvas.

¿Vas a proporcionar valor a los clientes que quieran consultar un API? ¿Está eso en el user journey? ¿Es algo que ya se puede solucionar mal que bien con el API actual de Discord y el lenguaje que sea (igual mejor que en C#)? Pues *no lo hagas* Define, de esa *cualquier cosa*, *qué* en concreto es lo que quieren hacer tus clientes.

> 
> De ahí del problema, que las herramientas que existen actualmente no permiten automatizar en un comando cualquier tarea. Se centran en enviar mensajes y poco más, si un usuario quiere un bot que (por ejemplo) haga peticiones PING a un servidor en China y luego postee un tweet con esa información, pues tiene que buscarse la vida programándolo él, porque las herramientas que hay no se lo permiten.

Ese es un ejemplo concreto de algo concreto que podía estar en un user journey, y sería un cliente concreto que necesita hacer ping a un servidor de China (por alguna razón). Recuerda, *no puedes resolver todos los problemas de todo el mundo*. Resuelve los problemas de *tus* clientes.

Además, si las herramientas actuales incluyen bibliotecas en el lenguaje de programación X que puede hacer ping a China, seguro que se puede resolver. Problema resuelto, siguiente.
> 
> > También tendrías que aclarar qué es "automatizar". Si es repetir con una frecuencia determinada, es simplemente repetir. Automatizar implicaría alguna forma de grabar las tareas.
> 
> Seguramente no lo esté expresando de la mejor manera, pero realmente automatizar es básicamente que el bot se encargue de ello. Si puedo crear y configurar un comando para que se haga cuando ejecuto !micomando en lugar de hacerlo yo a mano, ya estoy automatizando cosas.

Ya, pero también estás escribiendo a mano `!micomando`. Y hay quizás que programar las tareas.
> 
> > En todo caso, el problema es el habitual: sigues diciendo qué quiere hacer, no por qué quiere hacerlo. O mejor dicho, qué quiéres tú que él te pida, y no qué problema quiere resolver.
> 
> No lo veo de esa manera. Es cierto que el usuario no es el típico, ya que tiene conocimientos de programación y demás, y seguramente no lo esté expresando bien. El problema que quiere resolver es crear bots y comandos de manera sencilla, que le permitan hacer lo mencionado.

Si es programador, ¿por qué no usa una biblioteca de programación en el lenguaje elegido? Si lo que quieres es que sea fácil de desplegar o de otra cosa, ¿por qué no te centras en eso para cualquier bot escrito en cualquier lenguaje? 

Es totalmente válido que digas cosas como, no sé, hoy en día en la comunidad de juegos que usa Discord se está haciendo muy popular el lenguaje elixir y los programadores en este lenguaje no tienen una biblioteca para crear bots. Es un problema claro, con un cliente claro, y también una solución más o menos clara (aunque YMMV). Pero *claramente* estás proyectando una serie de cosas que no tienen nada que ver con un cliente que sabe programar, pero ¿por alguna razón no quiere hacerlo en este caso concreto? ¿Y además cuando lo haga, lo hace en C#?

> 
> > Si dejaras claro qué es lo que se automatiza
> 
> Cualquier tarea, la que el usuario quiera (siempre que sea programable, obviamente).

Entonces estás hablando de una biblioteca, básicamente, que en principio no tienen ningún tipo de restricción, sino que crean una capa de abstracción. Si no, volvemos a lo de antes: no tienes claro cuál es el problema que quieres resolver, y por tanto es imposible que lo resuelvas.
> 
> > y por qué se automatiza, quizás se entendería un poco mejor por qué quiere la gente automatizarlo.
> 
> Para que el usuario no tenga que hacerlo a mano. Ejecutar un comando y que el bot se encargue de hacer cosas es mucho más cómodo que tener que hacer esas cosas yo.
> 

¿No era un programador? ¿Un programador no es capaz de hacer cosas? ¿Ves como tienes que concretar qué cliente o clientes vas a usar y en qué casos concretos vas a solucionar su problema?

Porque si resulta que al final el cliente va a tener que programar, y hacerlo con una serie de restricciones que no tendría si usara una librería, va a usar una librería. Tienes *realmente* que ver el valor que vas a aportar al cliente o a los grupos de clientes.


> > Para el caso, es que no entiendo muy bien qué relación tiene Discord con el juego en sí, ni si se hacen cosas para juegos específicos, o simplemente canales específicos...
> 
> No entiendo lo del "juego". Discord es una plataforma muy utilizada últimamente, con integración de bots muy buena que permite hacer un montón de cosas. Se podrían crear bots para otras plataformas/apps, pero entre usuarios "programadores", lo que más veo que se use es Discord. Aparte, que el resto de usuarios no "programadores" también lo usan. Hay grupos de gente que lo usan para juntarse a jugar a X videojuego e integran bots para escuchar música o para moderar.

Has empezado hablando de videojuegos, y sin embargo sólo hablas de "funcionalidades" y "tareas", sin ninguna referencia a juego o juegos. Tienes que definir bien cuales con tus clientes. Si son quien usa Discord con juegos, tendrán un tipo de requisitos. Si son otros, son otros y tendrán otro tipo de requisitos. 

Por cierto, los programadores lo que más usan es Slack. Por eso volvemos al principio: tienes que definir el problema y en función de eso tomar decisiones técnicas sobre el proyecto.
> 
> > Siempre en un proyecto tienes que empezar por aclarar qué problema quieres resolver, si no todo se disuelve en ambigüedades, y sobre todo la "solución" que proporcionas es imposible saber si realmente soluciona algo.
> 
> [Aquí](https://github.com/harvestcore/matroos/pull/57) debería estar mejor definido el problema.

OK, vamos a ver.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\subsection{HU-02 - Editar bots y comandos}
Una HU tiene que expresar un beneficio para el usuario por la solución de un problema. Si le pones delante "ojala que yo pudiera" y "funciona", es una HU. Si no, es un issue o nada. "Ojalá que yo pudiera editar bots y comandos" no "funciona", porque no expresa ningún beneficio para el usuario (ni queda claro quién es el usuario).

Como ya te he dicho muchas veces, si pones la solución antes que el problema puedes exponerte a hacer código subóptimo o simplemente crear deuda técnica que no se use. Ya te lo he dicho muchas veces, dependiendo del problema, el usuario puede necesitar sólo bots configurables, inmutables y los comandos pueden ser también inmutables o simplemente específicos de cada bot.
En general, tienes que ver, usando domain driven design, la diferencia entre "entidades", "agregados" y "objetos valor", lo que influirá en la arquitectura del proyecto.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +        Resumen & Como usuario programador quiero disponer de un repertorio de comandos predefinidos ampliable para después crear comandos personalizados a partir de ellos. \\ \hline
Más o menos igual que arriba. No es una HU.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\subsection{HU-04 - Creación de comandos personalizados}
No es una HU.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\subsection{HU-05 - Interfaz de usuario}
No es una HU, ni siquiera puede serlo. En todo caso, un MVP.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +\subsection{HU-06 - Criterios de evaluación}
Sí es una HU.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +En esta sección se enumeran algunos \textit{user journeys} que podría realizar el usuario programador.
Los user journeys tienen que ser previos a las HUs, porque es de donde se sacan los problemas que hace falta que tú resuelvas para la clientela.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +La solución propuesta se caracteriza por ser software libre, pero los costos de desarrollo e implementación nunca son nulos.
No tiene nada que ver que sea software libre con el modelo de negocio.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +Debido a la muy probable falta de financiación al inicio del desarrollo del software, los objetivos iniciales se centrarían en obtener la renta mínima para poder continuar con el desarrollo del proye
Esto es externo al proyecto. Tienes que decir claramente cómo piensas obtener dinero.
Una vez más, el problema es que no sabes qué problema estás resolviendo ni para quién. Si el problema es suficientemente serio, quien sea pagaría dinero por tener el software que lo resolviera, con un modelo de software como servicio, instalación "on premises" o lo que sea. Si quieres programar "cualquier bot" para "cualquier cosa", está claro que "cualquier persona" no va a pagar dinero para eso.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +Como modelo de negocio, teniendo en cuenta que se opta por una solución compuesta por software libre, con el fin de sufragar todos estos gastos se podría optar por un modelo de consultoría. En este,
Si optas por consultoría, con quien consultes va a querer eventualmente cobrar por ello.
Si no obtiene dinero, no te va a pagar a ti para que desarrolles algo.
Una vez más, la ausencia de un problema concreto a resolver/cliente concreto que obtenga beneficio lastra todo el proyecto y sigue siendo un problema de base.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +Una \textit{SLNE} es una buena opción, ya que permite crear una pequeña empresa con pocos recursos iniciales con la que iniciar el desarrollo de forma profesional el desarrollo. Además tiene bastante
Esto es irrelevante si no tienes una fuente de ingresos. Y si lo que vas a ofrecer es consultoría, ser autónomo sería lo más razonable.

2022-06-08 16:39 UTC, JJ commented on doc/tex/secciones/03_analisis.tex
> +Se puede observar que el primer año de vida de esta empresa (que hasta el momento sólo tiene un empleado) costaría más de 43000 euros, una cifra bastante alta. En el caso de que se quisiera incluir a
¿Te das cuenta que en todo esto hay un fallo?

2022-06-14 18:50 UTC, merged