DOC-50 Add state of the art
harvestcore/matroos pull request #53
Opened 2022-05-26 20:36 UTC by harvestcore

This PR closes #50, by:

- Adding the documentation related to the state of the art.
  - Tools that exist nowadays to create Discord bots and commands.
  - Pros and cons.
  - Extra information

To get the PDF: Go to the latest [action artifact](https://github.com/harvestcore/matroos/actions).

Ps: I'm aware that the spacing between tables and other elements may be a bit off in some cases. I'm not worried about this. The documentation will change a lot, and all the spacing issues will be fixed when the final document is ready to be shipped.

2022-05-26 20:39 UTC, harvestcore commented
@JJ, 👀 cuando puedas, gracias!

2022-05-27 11:44 UTC, JJ requested changes
Adolece de los problemas habituales. Está escrito en general para una persona que a) está familiarizada con el contexto (y sabe qué significan las palabras: bot, servidor, despliegue, "comando") y segundo que ya tiene claro lo que va a hacer "Es como esto, pero...". Para una persona que quiere entender los problemas planteados y ver cómo se van tomando decisiones técnicas para solucionarlos, no queda nada claro cuáles son los retos planteados ni se explican bien las decisiones tomadas.

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En este capítulo se hace un repaso de las distintas soluciones actuales que existen para la creación de bots de \textit{Discord}. Cada una de ellas destaca en aspectos concretos, pero ninguna reúne t
Aquí estás diciendo
1. Voy a crear una herramienta para creación de bots de Discord
2. Otras herramientas hacen lo mismo.

Seguimos poniendo la solución antes que el problema. Cada herramienta tiene su clientela, y la tuya tiene la que has definido. Si hablas del problema, verás que hay muchas más herramientas que lo pueden solucionar
* Herramientas de automatización genéricas para cualquier sistema conversacional.
* Cosas del tipo IFTTT que automatizan tareas en web y mensajería (incluyendo email)
* Bots ya existentes.

Ya os lo he dicho muchas veces. Si partes de la base "existen soluciones actuales a esta cosa que yo estoy diciendo que voy a hacer" la reacción inmediata es: entonces la tuya no sirve para nada, porque ya hay otras. Sin embargo, si partes de una serie de problemas, y muestras cómo las herramientas existentes solucionan algo para alguien, pero no otras cosas que son las que tú quieres solucionar, entonces puedes establecer claramente que lo que tú has hecho supera a lo existente, y además comparar al final con lo que querías hacer (y lo existente) para ver que es mejor.

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En el ámbito de la creación de bots de \textit{Discord} existen una generosa cantidad de herramientas con este cometido. Como se comentaba en el capítulo anterior, estas herramientas en su basta mayo
*vasta*
Define "básico". ¿Qué problema que tú quieres resolver no resuelven?
No puedes partir de problemas indefinidos e imprecisos para decir "pero mi herramienta sí las resuelve". Ni decir que son básicos para decir "mi herramienta va a ser complicada". Usa casos de uso precisos, y di en qué no lo qiguen.
Si lo que tú vas a ofrecer es "interés" y "complitud" así como "simplicidad de uso", estos son tres requisitos *que tienes que demostrar que cumples*. También, por supuesto, demostrar de alguna forma que las actuales no lo cumplen (aludiendo a la bibliografía o a comparativas que queiras hacer tú)

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Estas herramientas permiten la creación de bots sin hacer uso de recursos de programación o similares. En la mayoría de casos estas plataformas cuentan con un único bot que se debe agregar al servido
¿Qué significa un único bot? ¿Que hay un bot que sólo puede hacer una cosa?

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +\href{https://probot.io/}{\textit{ProBot}} es sin duda la más interesante de las herramientas no-code debido a que permite crear ilimitados comandos personalizados, siendo la principal desventaja que
¿Y cómo los creas sin código?

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +        \textbf{Comandos reutilizables} & No \\ \hline
No sé qué significa esto. Tienes que explicar claramente qué significa cada cosa, porque si no no se entiende.

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +\href{https://autocode.com/}{Autocode} es sin duda la herramienta mas interesante que se ha encontrado de esta modalidad híbrida. Realmente es una plataforma que permite la creación y despliegue de a
Inyectado ¿dónde?

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +	\item Envío de un mensaje.
Esto no es un comando, es una tarea. Un comando es una orden, parte de un lenguaje o no, que es parametrizable.

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En las herramientas \textit{no-code} los bots se centran principalmente en tareas de moderación, envío de mensajes, estadísticas e integración con videojuegos y redes sociales. Se enfocan también en
O sea, son tareas, no comandos.

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +	\item No es posible crear comandos con funcionalidad específica.
O sea, no hay más tareas que la que hay predefinidas.

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +	\item No se pueden crear distintos bots.
¿Distintas combinaciones de tareas?

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En menos de 10 minutos se puede incluir una gran cantidad de funcionalidad a un servidor de manera gratuita, algo que puede ser muy útil para la basta mayoría de usuarios de \textit{Discord}, pero cu
¿Servidor? ¿Qué es un servidor? ¿Quién aloja los servidores?

2022-05-27 11:44 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En cambio, cuando se usan herramientas que hacen uso de código, el tiempo de implementación se incrementa considerablemente. Debido a las características de lenguajes como \textit{JavaScript} o \text
"en las que el usuario añade código"
Tampoco tiene sentido la comparación, son simplemente cosas diferentes. ¿Qué es más rápido, ejecutar un programa o hacerlo tú? Son simplemente cosas diferentes.

2022-05-31 19:24 UTC, harvestcore commented on doc/tex/secciones/03_estado_del_arte.tex
> +	\item Envío de un mensaje.
¿Por qué no es un comando? Por ejemplo:

> !help
> Hola. Este bot hace tal y cual.

---

En ese caso he puesto esos dos comandos como benchmark porque son los únicos que se pueden implementar en todos los sistemas que se mencionan, y por tanto puedo lo que se tarda en crearlos en cada una de ellas. En general los comandos que se pueden crear en las plataformas no-code son extremadamente básicos, y se basan en enviar mensajes, envío de mensajes cada X tiempo, o moderación.

2022-05-31 19:44 UTC, harvestcore commented
@JJ He actualizado teniendo en cuenta tus comentarios. Review cuando puedas, please.

2022-06-08 17:52 UTC, JJ requested changes
OK, estoy volviendo a repetir lo mismo de nuevo. Lo que tienes que tener en cuenta es que en un TFG no te juzgan por la solución, sino por lo que has sido capaz de hacer y solucionar para llegar a la misma. Por eso la metodología es tan importante, y mucho más en un TFM. Así que trata de hacer una metodología más sistemática, siempre sin partir de la solución para llegar al problema, sino partiendo del problema y tomando decisiones que te lleven a una solución probable y aceptable.

2022-06-08 17:52 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En este capítulo se hace un repaso de las distintas soluciones actuales que existen para la creación de bots de \textit{Discord} y la configuración de sus comandos.
soluciones para "la creación de bots" implica que el problema es "la creación de bots". Ese no es el problema, sin embargo, e incluso si lo es tienes que aclarar para quién.

2022-06-08 17:52 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Previa lectura de este capítulo es interesante conocer el significado de algunos conceptos que se usan.
No, tienes que aclarar el contexto y también aclarar si estás hablando de términos de interfaz de usuario o de definiciones técnicas desde el punto de vista del desarrollado (que es el que interesa en un TFM)

2022-06-08 17:52 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Las soluciones actuales se podrían dividir en dos grupos, herramientas \textit{no-code} y herramientas que hacen uso de programación. En ambas la interacción con el sistema se hace a través de una ap
Son soluciones a problemas diferentes para clientes diferentes. En ese sentido, **tienes que definir qué clientes vas a tener**

2022-06-08 17:52 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Estas herramientas permiten la creación de bots sin hacer uso de recursos de programación o similares. En general la mayoría de herramientas de este tipo tienen una serie de funcionalidades gratuitas
¿Por qué pagan y cuanto pagan?

2022-06-12 15:12 UTC, harvestcore commented
@JJ He aclarado todo teniendo en cuenta tus comentarios. Debería estar mejor ahora. Échale un ojo cuando puedas.

2022-06-13 16:06 UTC, JJ requested changes
Aunque algunas cosas se entienden un poco mejor, sigue sin estar muy focalizado en problema o problemas concretos.

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Los bots actúan como un usuario más dentro de un servidor de \textit{Discord}. En cambio, debido a su naturaleza, deben ser agregados a los servidores por usuarios humanos. Se pueden crear infinidad
Sigues sin distinguir el programa de su versión en funcionamiento. Uno es un programa, otro es un proceso. Los llamas a todos bot.
Tampoco tengo muy claro por qué "funcionalidades específicas" significa que "no pueden modificarse por los usuarios"

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +	\item \textbf{Comandos predefinidos}. Comandos cuya funcionalidad está ya definida (y por tanto programada) y no puede ser modificada por un usuario.
No puedes usar lo definido en la definición. "Un comando" es "un comando". ¿Qué es un comando?

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +    \item \textbf{Comandos de moderación}. Comandos cuya funcionalidad se centra en la moderación de usuarios en los servidores de \textit{Discord}.
Me da la impresión de que lo que tú llamas un comando es un patrón de código que se suele usar frecuentemente.

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +\section{Soluciones actuales}
Pero soluciones, ¿a qué?

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En las siguientes secciones se incluyen las herramientas con características más interesantes.
Interesantes, ¿para quién?
Un TFM es una exposición de las decisiones técnicas que has tomado a la hora de desarrollar un proyecto software. ¿Qué estás exponiendo aquí, exactamente?

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Estas funcionalidades predefinidas son en su mayoría de moderación de usuarios y envío de mensajes, y no se pueden reutilizar entre distintos bots. Además, debido a la estructura y arquitectura de es
Pero si mal no recuerdo uno de tus clientes era el que no tenía conocimientos de programación. Si estas herramientas solucionan el problema de este cliente, ¿qué valor le aportas tú?

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +\href{https://probot.io/}{\textit{ProBot}} es sin duda la más interesante de las herramientas \textit{no-code} debido a que permite crear ilimitados comandos personalizados, siendo la principal desve
¿En qué quedamos? ¿Son predefinidos o son personalizados?

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +De nuevo no es posible controlar el despliegue del bot, como tampoco es posible crear otro bot y agregarlo a un mismo servidor, o reutilizar comandos.
¿Qué es un servidor? ¿Dónde se ejecutan estos bots?

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Esta característica es muy interesante, pero está muy limitada y las funcionalidades que permite realizar se resumen en envío de mensajes y tareas de moderación de usuarios muy básicas. El plan \text
A menos que no quieras monetizar la herramienta sino darla gratis, el que sean premium no es una desventaja sobre la tuya. Y recuerda que no puedes *no* monetizar la herramienta, salvo que quieras crear una herramienta de software libre para programadores o algo así exclusivamente. Incluso así, debes buscar la forma de monetizarlo.

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Otro aspecto interesante es que se pueden crear distintos bots, hasta 50 distintos si se opta por la opción \textit{premium}.
¿Esto es relevante para entender las decisiones técnicas que has tomado en tu proyecto?

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Las librerías de programación dan libertad total a la hora de crear un bot de \textit{Discord}, lo cual puede ser ideal en algunos casos. Las ventajas son obvias, ya que se puede crear cualquier tipo
¿Qué complejidad tiene el despliegue?
No has hecho ningún tipo de introducción técnica al API de Discord ni lo que necesita. Generalmente, un despliegue es simplemente ejecutar un programa que lea un token el API. Lo puedes hacer en tu portátil si quieres.

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +Algunos ejemplos de librerías son:
El estado del arte tiene dos funcione
* Conoces lo que hay
* La solución que tú vas a presentar es mejor en algún aspecto

No se trata de un catálogo, ni se pretende que lo sea.

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +\end{itemize}
Tienes también bibliotecas que son agnósticas del sistema conversacional, mira aquí: https://botwiki.org/resources/libraries-and-frameworks/#bot-frameworks
En general, me da la impresión de que te fijas demasiado en Discord cuando la mayor parte de la definición técnica del proyecto sería bastante genérica.

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +	\item Envío de un mensaje.
> ¿Por qué no es un comando? Por ejemplo:
> 
> $ !help $ Hola. Este bot hace tal y cual.
> 

El comando es `!help`. La tarea es lo que se hace una vez interpretado el comando. `print` es un comando, imprimir es lo que se hace cuando se invoca el comando.

La distinción tienes que hacerla, y también distinguir el intérprete de comandos (que tendrás que programar) de las funciones a las que llama (sea desde bajo o alto nivel)

> En ese caso he puesto esos dos comandos como benchmark porque son los únicos que se pueden implementar en todos los sistemas que se mencionan, y por tanto puedo lo que se tarda en crearlos en cada una de ellas. En general los comandos que se pueden crear en las plataformas no-code son extremadamente básicos, y se basan en enviar mensajes, envío de mensajes cada X tiempo, o moderación.
> 
> Otros ejemplos que son comandos, ¿no?
> 
> !ban @harvestcore !tweet Hola que tal. !stats

Las órdenes son comandos, lo que hacen son tareas.
No acabo de entender muy bien qué se quiere tuitear desde Discord, pero no paras de decirlo, así que será importante.

Vuelvo de todas formas a lo mismo: Si pones una comparación de tiempo, es que el valor que vas a aportar tú es tardar menos; si es así, las soluciones técnicas que aportes estarán en el campo de UX, no tanto del resto. Insisto, tienes que tener muy claro qué problema vas a resolver, para quién, y cómo y qué vas a enfatizar como tu aportación en el TFM.

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +\end{itemize}
Te insisto, no puedes basar tu TFM en "lo mismo, pero gratis". Si es gratis, tienes que demostrar que no consume ningún tipo de recursos, o que has hallado una solución técnica para que sea gratis para el usuario (por ejemplo, lo ejecutan en su propio ordenador), pero que, a la vez, te reporte beneficios (porque si no aporta beneficios no es sostenible, simplemente).

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En el caso de las librerías de programación, aunque todas permiten el acceso a la \textit{API} de \textit{Discord}, cada una de ellas tiene una estructura distinta y los procedimientos para crear un
¿Y cuál es el problema? El usuario programador va a tener que programar de todas formas. Proporcionarle las herramientas necesarias para hacerlo fácilmente es lo suyo, más allá de interfaces de usuario. Además, es más justificable que no se monetice una biblioteca para programadores (porque no consume recursos)

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +\textit{Autocode} es una buena alternativa a las soluciones anteriores, ya que se evita el tener que gestionar el despliegue de los bots y se eliminan algunas trabas de gestión del código, pero al ig
Una vez más, identificar los problemas ayuda a aportar soluciones adecuadas. Si la "lógica recae en el usuario final", puedes aportar plantillas o ejemplos o generadores que ayuden al usuario final a crear bots rápidamente. Si el problema es el despliegue, puedes crear herramientas de despliegue. En cualquier caso tienes que focalizar tus esfuerzos de programación para aportar valor al cliente.

2022-06-13 16:06 UTC, JJ commented on doc/tex/secciones/03_estado_del_arte.tex
> +En la comparativa de tiempos anterior se puede observar que las herramientas \textit{no-code} son las más rápidas. Esto se debe a que solo es necesario agregar el bot al servidor de \textit{Discord}
No es un catálogo de venta de herramientas. Es una explicación técnica de los conceptos necesarios para desarrollar tu aplicación. "Agregar el bot al servidor" puede ser tan simple como pedir un API key específico de un servidor, o tan complejo como, no sé, pagar un proveedor *cloud* para que aloje tus bots y dar claves SSH para que el servidor conecte.
Hasta este momento no tengo claro qué implica el despliegue. Ni en qué se diferencia de desplegar un bot de Telegram, por ejemplo.

2022-06-14 18:21 UTC, merged