DOC-56 Define the problem and the target client in the introduction
harvestcore/matroos pull request #57
Opened 2022-05-31 18:41 UTC by harvestcore

Closes #56, #55 and #54.

---

He reescrito la introducción, teniendo en cuenta todos los detalles que has indicado en las issues enlazadas. He definido todos los conceptos clave al inicio, tras la introducción inicial. Además, he intentado limpiar el capítulo un poco, quitando contenido que no tenía especial relevancia.

Debería estar mejor ahora.

2022-06-08 16:40 UTC, JJ commented
> Closes #56, #55 and #54.
> 

Tienes que poner `closes` delante de cada issue.

2022-06-08 17:10 UTC, JJ requested changes
Te agradecería que le echaras un vistazo a las preguntas, concretando el problema a resolver. Si lo que quieres hacer es un "enlyft" (sea lo qeu sea) gratis, ya te digo que no va a funcionar, porque tienes que poner cómo vas a financiarlo. Si lo vas a hacer más barato u ofreciéndole más valor a los usuarios, tienes que concretar qué es lo que le vas a ofrecer y porqué es más barato o tiene más valor.
En resumen: concretar el problema y la clientela.

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Los bots son software que, mediante la ejecución de algoritmos, permiten automatizar tareas repetitivas de manera autónoma en un sistema. El uso de estos se ha popularizado mucho recientemente, tanto
Empiezas por lo que quieres hacer. Eso no es la introducción.

La introducción es "¡Se va a acabar el mundo! Pero no hay que preocuparse, porque en este TFM voy a hacer un app para que no se acabe"

La introducción tiene que contestar a las preguntas

1. ¿Qué problema hay en el mundo que quiero resolver?
2. ¿Por qué quiero resolver este problema, y qué probabilidades tengo de hacerlo en este TFM?
3. ¿Para quién quiero resolverlo en concreto y por qué para este grupo y no otros?
4. ¿Cómo pienso sacar dinero de todo ello, aunque sea para pagar el hosting?

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Con la creciente popularidad de los bots y de las plataformas sociales, cada día hay mas gente que quiere hacer uso de estos bots, ya sea por temas de trabajo o por que quieren pasar el rato, pero co
*Reference needed* para la popularidad.
En todo caso, esto no aclara absolutamente nada sobre el problema que quieres resolver. Queda claro que quieres hacer bots (sea lo que sea eso), pero poco más. Tienes que ser más concreto, y responder (como poco) a las preguntas que te digo antes.

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Previa introducción al problema concreto, en la siguiente sección se introducen todos aquellos conceptos y términos que se usan a lo largo de este documento, y que es útil conocer y comprender para l
El problema tiene que estar en la introducción. En la introducción sólo has hablado de los bots.

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Los comandos son órdenes o instrucciones concretas que se pueden ejecutar a voluntad de un usuario en cualquier momento. Se invocan haciendo uso de una palabra clave, aunque pueden ser también tareas
No veo que tengan tanta importancia como para ponerlos antes que bots. Pero si los pones, tendrías que explicar qué son desde el punto de vista del usuario (con pantallazos, por ejemplo) y desde el punto de vista técnico (cómo se hace parsing, cómo se reciben del servidor, etc, etc) Esta definición es demasiado superficial y genérica como para que vaya a satisfacer al tribunal (por cierto, me falta la HU concreta para enlazar)

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +\begin{itemize}
Por favor, trata de ser un poco más técnico aquí. Esas categorías no son ni excluyentes, ni tienen nada que ver la una con la otra, ni exhaustivas, ni nada. Quien no sepa que es un bot, va a seguir sin saberlo. Usa lenguaje más preciso, y ejemplos concretos (incluso poner un ejemplo básico en algún lenguaje de programación fácilmente comprensible (o sea, no C#))

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +\subsubsection{Sistemas de mensajería instantánea}
Definir esto antes que los bots... Yo qué sé. Ve de lo más general a lo más concreto...

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Es una aplicación de mensajería instantánea multiplataforma semejante a otras herramientas que se usan en ámbitos similares, como \textit{Slack} o \textit{TeamSpeak}, y ofrece distintos servicios de
No había oido hablar en mi vida de TeamSpeak, pero parece que es voz sobre IP. No sé si es eso lo que querías poner.

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +En \textit{Discord} los usuarios interactúan en \textbf{servidores}, que son comunidades construidas en torno a multitud de ámbitos, como por ejemplo deportes, cine o incluso en el mundo profesional.
Estás metiendo Discord si meter, en la motivación, por qué te fijas en él. Para el tribunal sólo va a ser más ruido, que no le va a ayudar a entender la motivación ni el beneficio del proyecto.
E, insisto, desde el punto de vista del programador no debes acoplar la funcionalidad de lo que quiera que sea que hagas a un API concreto (que es lo que es Discord). La decisión sobre concretar para este API debes hacerla lo más tarde posible.

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +\begin{itemize}
Un bot es un programa, existen las mismas facilidades que para cualquier otro programa. ¿Algo en concreto que quieras transmitir aquí?

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +La mejor manera de ilustrar el problema es con un ejemplo. Supongamos una pequeña empresa que utiliza \textit{Discord} como método de comunicación interna. Además, quieren utilizar bots como herramie
¿Por qué usan Discord y no Slack?
Una vez más, si te concentras en lo que quieres hacer, y no el problema que quieres resolver, puedes acabar haciendo cosas sin mucho sentido. La mayoría de las empresas usan Slack, de hecho, y tiene ya un montón de bots configurados para casi cualquier cosa.

2022-06-08 17:10 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +En el primer caso las herramientas son muy básicas y limitantes, no pudiendo adaptarse a las necesidades más complejas que podría tener un usuario más avanzado, como en el ejemplo. Además suelen basa
¿Qué limitan y para quién? Los bots de Slack sólo hacen lo que hacen, y es más que suficiente para cualquiera. Volvemos a la pregunta 0: ¿qué problema quieres resolver y para quién?
Si se basan en planes de pago, ¿quién paga y qué valor le añade? ¿Qué tipo de cosas se pagan? ¿La herramienta que tú hagas no va a ser de pago? ¿Cómo la vas a financiar entonces?

2022-06-11 10:00 UTC, harvestcore commented
@JJ Tienes razón. Después de los cientos de cambios que he hecho la introducción no estaba diciendo nada. La he reescrito teniendo en cuenta todo lo que has comentado y ahora creo que debería estar claro el problema y el cliente. Échale un ojo cuando puedas, please.

2022-06-13 16:32 UTC, JJ requested changes
Mientras no lleves a cabo el punto más básico, la motivación y la exposición del problema a resolver, no es posible entender bien qué se va a hacer y por qué.

2022-06-13 16:32 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Los bots son software que, mediante la ejecución de algoritmos, permiten automatizar tareas repetitivas de manera autónoma en un sistema. En los últimos años se ha popularizado mucho su uso, tanto es
Lo primero que tiene que ir en la introducción es la motivación y el problema que quieres resolver.

2022-06-13 16:33 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Previa introducción al problema concreto, en la siguiente sección se introducen todos aquellos conceptos y términos que se usan a lo largo de este documento, y que es útil conocer y comprender para l
Y esto sigue siendo un problema.

2022-06-13 16:34 UTC, JJ commented on doc/tex/secciones/01_introduccion.tex
> +Los bots son software que, mediante la ejecución de algoritmos, permiten automatizar tareas repetitivas de manera autónoma en un sistema. El uso de estos se ha popularizado mucho recientemente, tanto
¿De qué forma has contestado a estas preguntas? Te has limitado a reescribir lo que había antes, sin cambiar la estructura ni responder a esto. Por favor, trata de hacerlo, si es posible explícitamente.

2022-06-14 18:13 UTC, merged